### PR TITLE
Fix `Uncaught TypeError: options.icon.slice is not a function` when using `L.AwesomeMarkers.icon`  on startIcon and endIcon

### PR DESCRIPTION
**Pull request by SubiNesa**

### CODE REVIEW

**Comment by SubiNesa** [comment]
https://github.com/mpetazzoni/leaflet-gpx/issues/161

**Comment by mpetazzoni** [comment]
Thanks for the PR! This breaks setting icons for categories/waypoint types though, which are expected to be set with:

```js
markers: {
    wptIcons: {
      'Coffee shop': new L.AwesomeMarkers.icon({
        icon: 'coffee',
        prefix: 'fa',
        markerColor: 'blue',
        iconColor: 'white'
      })
    }
}
```

Can you find a way to tell those situations apart in `_prepare_markers()` ?

**Comment by SubiNesa** [comment]
Thanks for your comment.
I am little bit confused, wouldn't that be this line https://github.com/mpetazzoni/leaflet-gpx/blob/main/gpx.js#L292 ?

**Comment by mpetazzoni** [comment]
Ah yes you're right, I already had to handle that case because `type(null) === 'object'`

**Pull request merged**
